name: Build
on: 
    push: 
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout project
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1.4.2
              with:
                node-version: 12
            - name: Set Git parameters
              run: |
                git config --global user.name Penfoldium
                git config --global user.email crumbs@penfoldium.org
            - name: Install packages
              run: npm ci
            - name: Clone the build branch
              run: |
                mkdir build
                cd build
                git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/penfoldium/moonlight.git .
                git checkout build
            - name: Build project
              run: npx tsc
            - name: Add files to git and commit them
              run: |
                rsync -r ./dist ./build 
                rsync ./package* ./build
                cd build
                git add .
                git commit -m "build(): ${{ github.sha }}"
            - name: Push files to GitHub
              run: |
                cd build
                git push origin build