name: Build
on: 
    push: 
        branches:
            - master
jobs:
    compile:
        name: Compile
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout project
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1.4.2
              with:
                node-version: 12
            - name: Set Git parameters
              run: |
                git config --global user.name Penfoldium
                git config --global user.email crumbs@penfoldium.org
            - name: Install packages
              run: npm ci
            - name: Clone the compiled branch
              run: |
                mkdir compiled
                cd compiled
                git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/penfoldium/moonlight.git .
                git checkout compiled
            - name: Build project
              run: npx tsc
            - name: Add files to git and commit them
              run: |
                cp -r ./dist ./compiled/dist 
                cp ./package.* ./compiled
                cd compiled
                git add .
                git commit -m "Build ${{ github.sha }}"
            - name: Push files to GitHub
              run: |
                cd compiled
                git push origin compiled
    docs:
        name: Docs
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout project
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1.4.2
              with:
                node-version: 12
            - name: Set Git parameters
              run: |
                git config --global user.name Penfoldium
                git config --global user.email crumbs@penfoldium.org
            - name: Install packages
              run: |
                npm ci
            - name: Clone the gh-pages branch
              run: |
                mkdir gh-pages
                cd gh-pages
                git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/penfoldium/moonlight.git .
                git checkout gh-pages
            - name: Install typedoc and typescript
              run: npm install --global typedoc typescript
            - name: Build the docs
              run: typedoc
            - name: Add files to git and commit them
              run: |
                cp -a ./docs/. ./gh-pages 
                cd gh-pages
                git add .
                git commit -m "Docs ${{ github.sha }}"
            - name: Push files to GitHub
              run: |
                cd gh-pages
                git push origin gh-pages