name: Build
on: 
    push: 
        branches:
            - master
jobs:
    tsc:
        name: tsc
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout project
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1.4.2
              with:
                node-version: 12
            - name: Set Git parameters
              run: |
                git config --global user.name Penfoldium
                git config --global user.email crumbs@penfoldium.org
            - name: Install packages
              run: npm install
            - name: Clone the gh-pages branch
              run: |
                mkdir compiled
                cd compiled
                git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/penfoldium/moonlight.git .
                git checkout compiled
            - name: Build project
              run: npx tsc
            - name: Add files to git and commit them
              run: |
                cp -r ./dist ./compiled/dist 
                cp ./package.* ./compiled
                cd compiled
                git add .
                git commit -m "Build ${{ github.sha }}"
            - name: Push files to GitHub
              run: |
                cd compiled
                git push origin compiled